name: Docker Image CI

on:
  push:
    branches:
      - "production"
      - "stage"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build && push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }}
          build-args: VITE_API_ADDRESS=${{ vars.VITE_API_ADDRESS }}
          cache-from: type=registry,ref=${{ github.repository }}:buildcache
          cache-to: type=registry,ref=${{ github.repository }}:buildcache,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'production' || github.ref_name == 'stage' }}
    steps:
      - name: update server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.HOST_PORT }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: docker compose pull && docker compose up -d
  announce:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'production' }}
    steps:
      - name: announce update
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.HOST_PORT }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: ./announce.sh
